[env]
TERM = "alacritty"

[window]
opacity = 0.7
startup_mode = "Windowed"
decorations = "Buttonless"
padding = { x = 20, y = 20 }

# Blur (macOS/KDE Wayland only)
blur = true  # Default: false

# Option as Alt (macOS only)
option_as_alt = "Both"  # Default: "None"

[font]
normal = { family = "GeistMono Nerd Font", style = "Regular" }
bold = { style = "SemiBold" }
italic = { style = "Thin" }
bold_italic = { style = "UltraBlack" }
size = 18

[selection]
save_to_clipboard = true

# github dark default theme

# Default colors
[colors.primary]
background = '#0d1117'
foreground = '#b3b1ad'

# Normal colors
[colors.normal]
black   = '#484f58'
red     = '#ff7b72'
green   = '#3fb950'
yellow  = '#d29922'
blue    = '#58a6ff'
magenta = '#bc8cff'
cyan    = '#39c5cf'
white   = '#b1bac4'

# Bright colors
[colors.bright]
black   = '#6e7681'
red     = '#ffa198'
green   = '#56d364'
yellow  = '#e3b341'
blue    = '#79c0ff'
magenta = '#d2a8ff'
cyan    = '#56d4dd'
white   = '#f0f6fc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'

[keyboard]
bindings = [
    ### Zellij

    # Print char: `printf '\uE021'`

    { key = "T", mods = "Command",       chars = "\uF429" },
    { key = "N", mods = "Control",       chars = "\uF89C" },
    { key = "N", mods = "Command|Shift", chars = "\uF0FE" },
    { key = "R", mods = "Command",       chars = "\uF1FC" },
    { key = "B", mods = "Command",       chars = "\uF5CC" },
    { key = "M", mods = "Command",       chars = "\uF792" },
    { key = "O", mods = "Command",       chars = "\uF826" },
    { key = "F", mods = "Command",       chars = "\uF422" },
    { key = "W", mods = "Control",       chars = "\uF2D3" },
    { key = "Q", mods = "Control",       chars = "\uF090" },

    { key = "Left",  mods = "Shift", chars = "\uFC2F" },
    { key = "Right", mods = "Shift", chars = "\uFC32" },
    { key = "Up",    mods = "Shift", chars = "\uFC35" },
    { key = "Down",  mods = "Shift", chars = "\uFC2C" },

    { key = "Left",  mods = "Control|Shift", chars = "\uEA9B" },
    { key = "Right", mods = "Control|Shift", chars = "\uEA9C" },
    { key = "Up",    mods = "Control|Shift", chars = "\uEAA1" },
    { key = "Down",  mods = "Control|Shift", chars = "\uEA9A" },

    { key = "Left",  mods = "Option|Shift", chars = "\uF0D9" },
    { key = "Right", mods = "Option|Shift", chars = "\uF0DA" },
    { key = "Up",    mods = "Option|Shift", chars = "\uF0D8" },
    { key = "Down",  mods = "Option|Shift", chars = "\uF0D7" },

    { key = "Up",    mods = "Option",       chars = "\uF271" },
    { key = "R",     mods = "Option",       chars = "\uF448" },
    { key = "W",     mods = "Option",       chars = "\uF273" },
    { key = "Left",  mods = "Option",       chars = "\uF04A" },
    { key = "Right", mods = "Option",       chars = "\uF04E" },
    { key = "Left",  mods = "Option|Shift", chars = "\uF049" },
    { key = "Right", mods = "Option|Shift", chars = "\uF050" },

    { key = "Up", mods = "Command",        chars = "\uF106" },
    { key = "Down", mods = "Command",        chars = "\uF107" },
    { key = "Up", mods = "Command|Shift", chars = "\uF102" },
    { key = "Down", mods = "Command|Shift", chars = "\uF103" },
    { key = "Up", mods = "Command|Option|Shift", chars = "\uF6BB" },
    { key = "Down", mods = "Command|Option|Shift", chars = "\uF6BA" },
]